### ISSUE TITLE
UTF-8 Links seem to cause issues.

### ISSUE THREAD

**Issue by ZenHarbinger** [artistech-inc/social-media-scraper#10]
https://muraselon.com/2017/10/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D8%A7%D8%B3%D8%AA%D8%B3%D9%84%D8%A7%D9%85-%D9%85%D8%B3%D9%84%D8%AD%D9%8A-%D8%AF%D8%A7%D8%B9%D8%B4-%D8%A7%D9%84%D8%B3%D9%88%D8%B1%D9%8A%D9%8A%D9%86-%D9%84%D9%82%D9%88/

Seems to hang on this URL halting all work.  I don't think it was found in v0.9 since that used a regex to extract links instead of pulling it from the tweet metadata.

**Comment by jmhai** [comment]
I'm fairly certain that Matt fixed this one.
